# Generated by Django 2.2.5 on 2019-11-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191105_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile')], max_length=13, verbose_name='Ícones'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile')], max_length=13, verbose_name='Ícone'),
        ),
    ]
