# Generated by Django 2.2.5 on 2019-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191104_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('Ini_status-up', 'Gráfico'), ('Ini-mobile', 'Mobile'), ('Ini-rocket', 'Foguete'), ('Ini_cog', 'Engrenagem'), ('Ini-layers', 'Design'), ('lni-users', 'Usuários')], max_length=13, verbose_name='Ícone'),
        ),
    ]
