# Generated by Django 2.2.5 on 2019-11-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191105_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Laptop'), ('lni-mobile', 'Mobile'), ('lni-leaf', 'Folha'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='Ícones'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico')], max_length=13, verbose_name='Ícone'),
        ),
    ]
