# Generated by Django 2.2.5 on 2019-11-04 21:30

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191104_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('Ini_status-up', 'Gráfico'), ('lni-users', 'Usuários'), ('Ini-mobile', 'Mobile'), ('Ini_cog', 'Engrenagem'), ('Ini-layers', 'Design'), ('Ini-rocket', 'Foguete')], max_length=13, verbose_name='Ícone'),
        ),
    ]
