# Generated by Django 2.2.5 on 2019-11-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191104_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni_status-up', 'Gráfico'), ('lni-mobile', 'Mobile'), ('lni_cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design')], max_length=13, verbose_name='Ícone'),
        ),
    ]
