# Generated by Django 2.2.5 on 2019-11-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191105_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Laptop'), ('lni-leaf', 'Folha'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile')], max_length=16, verbose_name='Ícones'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile')], max_length=13, verbose_name='Ícone'),
        ),
    ]
