# Generated by Django 2.2.5 on 2019-11-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191104_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-status-up', 'Gráfico'), ('lni-layers', 'Design')], max_length=13, verbose_name='Ícone'),
        ),
    ]
