# Generated by Django 2.2.5 on 2019-11-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191105_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-users', 'Usuários')], max_length=13, verbose_name='Ícone'),
        ),
    ]
