# Generated by Django 2.2.5 on 2019-11-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191105_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-users', 'Usuários'), ('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='Ícone'),
        ),
    ]
