# Generated by Django 2.2.5 on 2019-11-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191114_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Laptop'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem')], max_length=16, verbose_name='Ícones'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem')], max_length=13, verbose_name='Ícone'),
        ),
    ]
